language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g bower
  - bower install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
 - ./node_modules/karma/bin/karma start - istanbul cover ./node_modules/mocha/bin/_mocha server/api//.spec.js - cat ./coverage/lcov.info ./coverage/karma//.info > lcov.info - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage