language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g bower
  - bower install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  code_climate:
    repo_token: 4f0d28dcf42f85e76c87593f3aa94573a0ff2189957421eadaa8b52e31700e54
after_script:
  - cat coverage/lcov.info | codeclimate